[FTK-40]알림 설정 페이지 퍼블리싱
yumis-coconudge/50k-web pull request #13
Opened 2023-10-10 09:10 UTC by leegilhak

# 작업 내용

알림 설정 페이지 퍼블리싱 작업

# 작업 결과

<img width="360" alt="image" src="https://github.com/yumis-coconudge/50k-web/assets/75301843/9ecac524-92a5-4161-a255-4673ddb83856">

# 관련 이슈

- https://www.notion.so/wavleworks/1e01f91f235f4b56b445a89b0127217b?pvs=4

# 추가적으로 확인 할 사항

- [ ]

2023-10-10 09:53 UTC, heum-jh approved these changes

2023-10-11 01:46 UTC, YDisa approved these changes

2023-10-11 01:57 UTC, heum-jh requested changes

2023-10-11 01:57 UTC, heum-jh commented on src/components/common/togle-switch.tsx
> +      <div className="peer h-[1.25rem] w-[2.25rem] rounded-full bg-[#E6E8EC] after:absolute after:left-[0.125rem] after:top-[0.125rem] after:h-[1rem] after:w-[1rem] after:rounded-full after:border af
tailwind css의 기본 orange-500색상과 피그마에서 보이는 색상과는 다른값입니다.
tailwind css의 기본 orange-500색상은 `#F97316`이고
디자인의 색상은 `#FF7314` 입니다.
피그마에서 제공하는 HEX 값으로 색상을 설정해야합니다.

border-gray-300 도 변경해야합니다.

2023-10-12 01:58 UTC, heum-jh approved these changes

2023-10-12 04:51 UTC, taehwajangwavle approved these changes

2023-10-12 05:25 UTC, merged