[FTK-32]  마이페이지 작업
yumis-coconudge/50k-web pull request #25
Opened 2023-10-17 03:49 UTC by taehwajangwavle

# 작업 내용

 - 마이페이지 게시물 , 모임 , 북마크 
 

# 작업 결과

<img width="406" alt="스크린샷 2023-10-17 오후 12 23 12" src="https://github.com/yumis-coconudge/50k-web/assets/97080197/f188a573-2d68-4396-b341-ce590f312218">
<img width="417" alt="스크린샷 2023-10-17 오후 12 23 06" src="https://github.com/yumis-coconudge/50k-web/assets/97080197/667e8e93-415b-4171-ba0b-be895610b2be">
<img width="447" alt="스크린샷 2023-10-17 오후 12 22 58" src="https://github.com/yumis-coconudge/50k-web/assets/97080197/ea27fe45-cac8-43d0-ac3e-01ec3c4871f0">

# 관련 이슈

-

# 추가적으로 확인 할 사항

- [ ]

2023-10-17 07:46 UTC, YDisa approved these changes

2023-10-17 07:54 UTC, leegilhak approved these changes

2023-10-17 08:03 UTC, leegilhak approved these changes

2023-10-18 02:26 UTC, heum-jh requested changes

2023-10-18 02:26 UTC, heum-jh commented on src/components/meeting/board-tab.tsx
> +            <MeetingBoardCard isMine={true} key={index} onClick={() => router.push("/metting/board/123")} />
병합에 문제가 있었습니다.
metting => meeting로 수정되었습니다.

2023-10-18 02:29 UTC, heum-jh approved these changes

2023-10-18 02:34 UTC, merged