[FTK-74] 이용약관 API 연결
yumis-coconudge/50k-web pull request #29
Opened 2023-10-18 08:39 UTC by xodnjs0876

# 작업 내용
이용약관 API 연결

# 작업 결과
<img width="500" alt="스크린샷 2023-10-18 오후 5 31 28" src="https://github.com/heum-jh/web-starter/assets/141001234/fe3d246b-74df-4393-8d5c-1da9b695262a">
<img width="388" alt="스크린샷 2023-10-18 오후 5 31 34" src="https://github.com/heum-jh/web-starter/assets/141001234/ef1fd110-7056-45b3-acc0-8e4b2a4266a0">

# 관련 이슈
https://www.notion.so/wavleworks/API-1af3588c102d428198bbad030db10979?pvs=4

-

# 추가적으로 확인 할 사항
- [ ]

2023-10-18 09:56 UTC, YDisa requested changes

2023-10-18 09:56 UTC, YDisa commented on src/core/graphql/query/terms-of-service.graphql
서비스내 각각의 이용약관을 id가 아닌 고유 URL로 제작되어야합니다.

@leegilhak 확인요

2023-10-18 10:21 UTC, heum-jh commented on src/core/graphql/query/terms-of-service.graphql
해당사항 가온님에게도 전달 했습니다.

2023-10-19 01:45 UTC, heum-jh requested changes

2023-10-19 01:45 UTC, heum-jh commented on src/pages/policy/[id].tsx
> +  const { data } = useTermsOfServiceQuery({
이용약관 경우는 SSR 방식으로 데이터를 가져오는게 좋습니다.
현재 사용한 방식은 SSR이 된 이후 데이터를 불러오고 있습니다.
해당 부분 처리 진행해주셔야합니다.

2023-10-24 08:28 UTC, YDisa requested changes

2023-10-24 08:28 UTC, YDisa commented on src/pages/policy/index.tsx
>        <ul className="flex  flex-col ">
데이터가 없을 상황을 고려하여 알맞는 문구를 넣어주세요.

2023-10-24 12:00 UTC, heum-jh commented
master 기준으로 `src/pages/_app.tsx` 수정해주세요.
@xodnjs0876

2023-10-24 12:00 UTC, heum-jh approved these changes

2023-10-25 01:03 UTC, YDisa commented
edc2d888c5413da4b21413b55862cc608fe18fad 머지가 잘못되어 master 코드가 아닌 current branch 코드로 병합된것을 확인
커밋 reset 후 재작업 진행으로합니다.

2023-10-25 01:03 UTC, closed without merging