FTK_3 sns  로그인 페이지
yumis-coconudge/50k-web pull request #3
Opened 2023-10-06 04:02 UTC by taehwajangwavle

# 작업 내용

 - sns 로그인 페이지

# 작업 결과

<img width="431" alt="스크린샷 2023-10-06 오전 11 47 17" src="https://github.com/yumis-coconudge/50k-web/assets/97080197/b5db8416-7704-451a-9db2-63877054da26">

# 관련 이슈

-

# 추가적으로 확인 할 사항

- [ ]

2023-10-06 05:45 UTC, leegilhak approved these changes

2023-10-06 05:46 UTC, heum-jh approved these changes

2023-10-06 06:38 UTC, heum-jh requested changes
디바이스의 세로길이에 따라서 해당 페이지는 영향을 많이 받습니다.
같이 올려주신 스크린샷에서도 동일하게 해당부분을 확인할 수 있으니
세로길이에 영향을 받지 않게 수정해주세요.

2023-10-09 23:52 UTC, YDisa approved these changes

2023-10-10 00:21 UTC, heum-jh approved these changes

2023-10-10 00:39 UTC, merged