[FTK-43] 카카오 회원가입,  이용약관 api 추가
yumis-coconudge/50k-web pull request #31
Opened 2023-10-19 02:46 UTC by taehwajangwavle

# 작업 내용

 - 카카오 회원가입 추가 
 - 약관동의 리스트 api 추가 

# 작업 결과

<img width="1035" alt="스크린샷 2023-10-19 오전 11 45 10" src="https://github.com/yumis-coconudge/50k-web/assets/97080197/13db55a9-4496-42ea-b2c4-086774579a35">

# 관련 이슈

-

# 추가적으로 확인 할 사항

- [ ]

2023-10-20 02:48 UTC, YDisa approved these changes

2023-10-20 07:25 UTC, taehwajangwavle commented
휴대폰 번호 인증 작업 추가로 보류하겠습니다.

2023-10-23 08:24 UTC, heum-jh requested changes

2023-10-23 08:24 UTC, heum-jh commented on src/components/login/profile.tsx
>                    type="number"
IOS에서 number를 사용할 때는 
`pattern="\d*"` 를 추가 해주세요.

2023-10-23 08:24 UTC, heum-jh commented on src/pages/profile/index.tsx
> +              <button
button의 onClick 이벤트가 아닌 form 태그에 적용되어야 합니다.

2023-10-23 08:30 UTC, heum-jh approved these changes

2023-10-23 08:31 UTC, leegilhak approved these changes

2023-10-23 08:31 UTC, merged