[FTK-71] 1대1 문의 리스트/작성 API 연결
yumis-coconudge/50k-web pull request #35
Opened 2023-10-23 06:00 UTC by xodnjs0876

# 작업 내용
1대1 문의 리스트/작성 API 연결

# 작업 결과
<img width="388" alt="스크린샷 2023-10-23 오후 2 56 02" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/e3874eeb-3084-4f81-841c-f87cf7c64103">
<img width="387" alt="스크린샷 2023-10-23 오후 2 56 06" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/f1472ad2-f177-41f1-bf08-517abb5742cc">
<img width="391" alt="스크린샷 2023-10-23 오후 2 56 22" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/3b0c2869-d9ac-4021-a368-4782c93fb062">

# 관련 이슈

-https://www.notion.so/wavleworks/1-1-API-d115fbe89105436db5f722b4513e33e6?pvs=4

# 추가적으로 확인 할 사항

- [ ]

2023-10-23 06:43 UTC, heum-jh requested changes

2023-10-23 06:43 UTC, heum-jh commented on src/components/common/insert-image.tsx
> +  }, [selectedImage]);
해당 userEffect는 용도는 무엇인가요?

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/write.tsx
> +          <button type="button" className="text-base font-medium text-[#A2A9B5]" onClick={registerInquire}>
제목과 내용이 빈 값일 때는 text 색상이 #A2A9B5가 맞습니다.
제목과 내용이 빈 값이 아닐 때는 #FF7314 색상이 되어야 합니다.

또한 빈 값일 때는 등록이 되면 안됩니다.
수정 페이지도 동일합니다.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/[id].tsx
> +        imageUrl={data?.inquire.files?.map(item => item.url)}
PopoverImage가 fill이 아니라서 꽉차게 나오지 않네요.
width, height 대신 fill로 변경해주세요.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/index.tsx
> +        return "답변 대기중";
`답변 대기중`이 아닌 `답변 대기`입니다.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/modify.tsx
> +  const onChangeFiles = (files: ImageProps[]) => {
수정 시, 파일을 업로드 할 때 기존의 파일도 같이 날라가게 됩니다.
기존의 파일은 유지하되 새로운 파일이 추가될 수 있게 해주세요.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/modify.tsx
> +          <button className="text-base font-medium text-[#A2A9B5]" onClick={handleUpdate}>
동일합니다.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/[id].tsx
> +                    onDeleteInquire(router.query.id as string);
삭제 시 confirm이 없습니다. 추가해주세요.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/modify.tsx
> +      router.replace(`/inquiry/${updateData?.updateInquire.id}`);
`push`가 아닌 `replace` 를 사용한 이유가 있나요?
다른 곳 들도 동일합니다.

2023-10-23 06:43 UTC, heum-jh commented on src/pages/inquiry/modify.tsx
> +    } catch (error) {
Apollo graphq를 사용을 해서 try catch를 사용할 때 
catch에서 단순하게 console.log로 에러 핸들링을 하기 보다
message를 띄워 주셔야 오류 사항을 알 수 있습니다.
해당 부분 다른 작업들을 참고하여 수정 해주세요.

2023-10-23 06:48 UTC, xodnjs0876 commented on src/components/common/insert-image.tsx
> +  }, [selectedImage]);
handleRemove 함수를 돌리고 난 뒤에 onChange로 값을 넘어가게 두었더니 useState배열의 값이 삭제가 되긴 전의  값이 넘어가게 되어서 useEffect를 사용해서 값이 바뀔때마다 값이 넘어가게 해줬습니다.

2023-10-23 06:52 UTC, xodnjs0876 commented on src/pages/inquiry/modify.tsx
> +      router.replace(`/inquiry/${updateData?.updateInquire.id}`);
수정이나 삭제 후 뒤로가기를 했을 때 수정 페이지나 삭제한 페이지로 못 넘어가게 하기 위해서 사용했습니다.

2023-10-24 02:22 UTC, heum-jh commented
`src/core/graphql/index.ts` 병합 오류 문제는 강제 병합 후 `generate` 후 push 진행해주세요.

2023-10-24 02:27 UTC, heum-jh requested changes

2023-10-24 02:27 UTC, heum-jh commented on src/pages/inquiry/write.tsx
> +      ;
`;`해당 부분 삭제해주세요

2023-10-24 02:27 UTC, heum-jh commented on src/pages/meeting/board/modify.tsx
> +        imageUrl={[{ name: "test.png", url: "https://via.placeholder.com/300x300?text=test", type: "" }]}
해당 코드는 퍼블리싱 단계에서 임시로 보여주려고 추가한 코드 입니다.
정상적인 데이터로 변경해주세요.

2023-10-24 02:32 UTC, xodnjs0876 commented on src/pages/meeting/board/modify.tsx
> +        imageUrl={[{ name: "test.png", url: "https://via.placeholder.com/300x300?text=test", type: "" }]}
해당 파일 부분은 imageProp을 사용해서 타입 오류가 발생해서 고친 파일입니다. API 연결 진행 중인 페이지가 아닙니다.

2023-10-24 02:50 UTC, heum-jh approved these changes

2023-10-24 06:28 UTC, leegilhak commented on src/core/function/upload-file.ts
@xodnjs0876 해당 부분 uploadFile함수 변경 다른곳에서도 사용되고 이미 다른 branch에서도 사용하고 있는데 변경한 이유가 있을까요?

2023-10-24 06:32 UTC, xodnjs0876 commented on src/core/function/upload-file.ts
@leegilhak 이미지 업로드하는 부분에서 전체적으로 타입이 맞지 않고 이미지 업로드 시 여러개가 동시에 업로드 되지 않아서 바꾸게 되었습니다.

2023-10-24 06:45 UTC, leegilhak commented on src/core/function/upload-file.ts
@xodnjs0876 해당 파일 마스터껄로 pull 받고 만약 uploadFile함수 쓰는부분 바뀐부분있으면 원래대로 돌려주시고 blob 형식에서 file타입으로 바꾸는 작업 uploadFile함수 사용전에 변환해서 보내주세요.

2023-10-24 08:29 UTC, YDisa approved these changes

2023-10-25 00:45 UTC, leegilhak approved these changes

2023-10-25 01:06 UTC, YDisa commented
68c1e63858511ae78f840ef5fc63f48d5be3bae7 해당 머지도 잘못 병합되어 재작업 필요

@xodnjs0876

2023-10-25 01:06 UTC, closed without merging