feat: 자주 묻는 질문 API 연결
yumis-coconudge/50k-web pull request #36
Opened 2023-10-23 07:32 UTC by yoonho219

# 작업 내용
자주 묻는 질문 API 연결

# 작업 결과
<img width="370" alt="스크린샷 2023-10-23 오후 4 28 26" src="https://github.com/heum-jh/web-starter/assets/141003270/56e9d902-f6a1-4efc-a77c-0dbc91a644b1">
<img width="370" alt="스크린샷 2023-10-23 오후 4 28 22" src="https://github.com/heum-jh/web-starter/assets/141003270/0cf6bddd-5142-4cb4-98b0-6712be6e11da">

# 관련 이슈
-https://www.notion.so/wavleworks/API-f90efee821f1430f94f5de4266dee388?pvs=4

# 추가적으로 확인 할 사항
- [ ]

2023-10-23 07:36 UTC, heum-jh requested changes

2023-10-23 07:36 UTC, heum-jh commented on src/pages/my/faq.tsx
> +  const { data: faqData } = useAdminPostsQuery();
SSR 방식으로 진행해주세요.

2023-10-24 01:47 UTC, heum-jh requested changes

2023-10-24 01:47 UTC, heum-jh commented on src/pages/my/faq.tsx
> +export const getServerSideProps: GetServerSideProps = async ({ req, res, query }) => {
getServerSideProps를 추가만 하셨지 실제로 사용하고 있지는 않네요.

2023-10-24 01:49 UTC, heum-jh commented on src/pages/my/faq.tsx
> +export const getServerSideProps: GetServerSideProps = async ({ req, res, query }) => {
실제로 사용할 수 있게 수정해주세요. SSR 방식으로 바꾸면서 기존에 있던 코드는 필요가 없어지겠죠

2023-10-24 02:13 UTC, yoonho219 commented on src/pages/my/faq.tsx
> +export const getServerSideProps: GetServerSideProps = async ({ req, res, query }) => {
제가 이해를 잘못 했던 거 같습니다.
아래 사진처럼 수정 했는데 어디서 사용해야 할지 알려주실 수 있을까요??
![스크린샷 2023-10-24 오전 11 04 31](https://github.com/yumis-coconudge/50k-web/assets/141003270/6526d3e0-4fff-4ac4-a6b6-400b73a5e022)

2023-10-24 02:20 UTC, heum-jh approved these changes

2023-10-24 08:27 UTC, YDisa requested changes

2023-10-24 08:27 UTC, YDisa commented on src/pages/my/faq.tsx
>        <ul className="flex  flex-col ">
리스트 형태에서는 기본적으로 리스트가 없을시 보여줄 문구도 추가해주세요

2023-10-25 00:30 UTC, YDisa requested changes

2023-10-25 00:30 UTC, YDisa commented on src/pages/my/faq.tsx
> +        "자주 묻는 질문이 없습니다."
@leegilhak 리스트 없을시의 문구 디자인 가이드 필요

2023-10-25 02:09 UTC, YDisa approved these changes

2023-10-25 02:21 UTC, leegilhak approved these changes

2023-10-25 06:05 UTC, taehwajangwavle approved these changes

2023-10-25 06:15 UTC, merged