[FTK-55] 공지사항 리스트/상세페이지 API 연결
yumis-coconudge/50k-web pull request #37
Opened 2023-10-24 08:30 UTC by xodnjs0876

# 작업 내용

공지사항 리스트/상세페이지 API 연결

# 작업 결과

<img width="388" alt="스크린샷 2023-10-24 오후 5 26 13" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/236b3365-f0e4-492f-8d8c-2936e6dc4b8c">
<img width="387" alt="스크린샷 2023-10-24 오후 5 26 16" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/d7ffb1d3-2110-48ad-964a-cb305260e31b">

# 관련 이슈

-https://www.notion.so/wavleworks/API-857e27bb1cd94e44a98ed62c60daa400?pvs=4

# 추가적으로 확인 할 사항

- [ ]

2023-10-24 11:59 UTC, heum-jh requested changes

2023-10-24 11:59 UTC, heum-jh commented on src/pages/notice/[id].tsx
> +const NoticeDetailPage: NextPageWithLayout<AdminPostQuery> = data => {
`AdminPostQuery | undefined`로 해서 data가 없을 때도 type 체크 해줘야합니다.

2023-10-24 11:59 UTC, heum-jh commented on src/pages/notice/[id].tsx
> +      {data.adminPost && (
이렇게 되면 아무것도 없는 빈 화면만 나옵니다.
Alert를 보여주고 redirect하거나 옵셔널 처리하거나 수정해주세요.
옵셔널 처리는 이런식으로 진행하시면 됩니다.
```typescript
data.adminPost?.title ?? "-"
data.adminPost?.title ?? ""
```

2023-10-24 11:59 UTC, heum-jh commented on src/pages/notice/index.tsx
> +  const { data } = useAdminPostsQuery({
getServerSideProps를 이용해주세요

2023-10-25 03:08 UTC, heum-jh approved these changes

2023-10-25 04:30 UTC, YDisa requested changes

2023-10-25 04:30 UTC, YDisa commented on src/pages/notice/[id].tsx
> +    Alert.alert("데이터가 존재하지 안습니다.");
getServerSideProps에서 notfound로 처리되게 해주세요.

그리고 data가 없다고 얼럿창으로 띄우기만하는게 아닌 후속 처리까지 고려해주세요.
위와 같은 경우에서는 얼럿 후 이전 페이지 혹은 admin post index로 이동해야합니다.

2023-10-25 06:06 UTC, taehwajangwavle approved these changes

2023-10-25 06:17 UTC, YDisa approved these changes

2023-10-25 08:31 UTC, leegilhak approved these changes

2023-10-25 08:32 UTC, merged