feat: 계정 관리 API 연결
yumis-coconudge/50k-web pull request #44
Opened 2023-10-26 08:46 UTC by xodnjs0876

# 작업 내용

계정 관리 API 연결

# 작업 결과

<img width="389" alt="스크린샷 2023-10-26 오후 5 43 01" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/3127e3d7-052c-4c8a-b579-485b4d24a008">
<img width="397" alt="스크린샷 2023-10-26 오후 5 43 23" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/d2b4cd0d-3ef2-4a61-8652-8923c32f7782">
<img width="394" alt="스크린샷 2023-10-26 오후 5 43 36" src="https://github.com/yumis-coconudge/50k-web/assets/141001234/f8454920-d2e9-4160-ab36-37ffeb0b723d">

# 관련 이슈

- https://www.notion.so/wavleworks/API-7545b8a3935e4032a6bac20791aa6f5c?pvs=4

# 추가적으로 확인 할 사항

- [ leaveUserMutation reason 값 수정 필요]

2023-10-26 09:09 UTC, YDisa requested changes

2023-10-26 09:09 UTC, YDisa commented on src/pages/account/leave.tsx
> +              }
Error 타입이 아닐 경우가 없겠지만 else인 경우를 고려해주세요.

2023-10-26 09:09 UTC, YDisa commented on src/pages/account/leave.tsx
> +              }
비슷한 다른 곳도 수정요

2023-10-26 09:15 UTC, heum-jh reviewed
`button` 태그에서 disabled를 사용하신다면
`className` 에서 `disabled:` tailwind 문법을 사용해주세요.

2023-10-26 09:15 UTC, heum-jh commented on src/pages/account/index.tsx
게정관리 router 구조가 틀렸습니다.
마이페이지 > 설정 > 계정관리 입니다.

2023-10-27 00:51 UTC, xodnjs0876 commented on src/pages/account/index.tsx
url 구조가 my/setting/account 이런 식으로 넘어오는 것을 말하시는건가요?

2023-10-27 02:09 UTC, YDisa commented on src/pages/account/leave.tsx
> +              }
@xodnjs0876 이 부분 반영안됬습니다

2023-10-27 02:11 UTC, xodnjs0876 commented on src/pages/account/leave.tsx
> +              }
stash에 올린것을 모르고 커밋을 안 했습니다.
방금 커밋 올렸습니다.

2023-10-27 02:13 UTC, YDisa requested changes

2023-10-27 02:13 UTC, YDisa commented on src/pages/my/setting/account/leave.tsx
> +                Alert.alert("잘못된 요청입니다.");
잘못된 요청입니다 -> 탈퇴처리간 오류가 발생했습니다./n관리자에게 문의해주세요.

2023-10-27 02:13 UTC, YDisa commented on src/pages/my/setting/account/phone-modify.tsx
> +        Alert.alert("잘못된 요청입니다.");
잘못된 요청입니다 -> 휴대폰번호 변경간 오류가 발생했습니다../n잠시 후 다시 시도해주세요.

2023-10-27 06:29 UTC, heum-jh approved these changes

2023-10-27 06:29 UTC, taehwajangwavle approved these changes

2023-10-27 06:34 UTC, YDisa approved these changes

2023-10-27 07:49 UTC, leegilhak approved these changes

2023-10-27 07:49 UTC, merged