FTK-6 프로필 작성하기 페이지 작업
yumis-coconudge/50k-web pull request #6
Opened 2023-10-06 06:47 UTC by taehwajangwavle

# 작업 내용

 - 프로필 작성하기 페이지 작업

# 작업 결과

<img width="543" alt="스크린샷 2023-10-06 오후 3 42 12" src="https://github.com/yumis-coconudge/50k-web/assets/97080197/0eb2fedc-e9fc-4fd0-b563-a20fbb4331aa">

# 관련 이슈

-

# 추가적으로 확인 할 사항

- [ ]

2023-10-06 07:01 UTC, YDisa approved these changes

2023-10-06 07:36 UTC, heum-jh requested changes

2023-10-06 07:36 UTC, heum-jh commented on src/pages/profile.tsx
> +          <span className="text-[0.875rem]/[1.25rem] font-semibold text-[#111111]">닉네임</span>
label과 input사이의 간격이 없습니다. 추가해주세요.

2023-10-06 07:36 UTC, heum-jh commented on src/pages/profile.tsx
> +                  {secondsToTime(count)}
해당 로직은 (한외협)[https://github.com/yumis-coconudge/kfiri-web/blob/master/src/core/hooks/use-countdown.tsx]를 참고해서 작업해주세요.

translate-y-[-50%] 대신 translate-y-1/2를 사용할 수 있습니다.
음수 값을 표현할 때는 -translate-y-1/2로도 할 수 있습니다.

2023-10-06 07:36 UTC, heum-jh commented on src/pages/profile.tsx
> +              <div className="w-335 relative mt-2">
가급적 width, height의 값들은 고정으로 하지 말아주세요.
padding과 margin을 활용해주세요.
또한 해당 프로젝트에서 w-335는 없는 문법입니다.

2023-10-06 07:36 UTC, heum-jh commented on src/pages/profile.tsx
> +          <button
기본적으로 type="button" 추가해주세요

2023-10-10 00:40 UTC, leegilhak approved these changes

2023-10-10 00:40 UTC, merged